#!/bin/bash


ID=$(docker ps | grep tor | cut -d" " -f1,1)
if [[ -z $ID ]]; then
    echo "Starting container"
    ID=$(docker run -d tor:$1)
else
    echo "Container already running, ID: $ID"
fi

IP=$(docker inspect $ID | sed -n 's/.*ress": "\(.*\)",$/\1/p')
echo $IP
if [ -z $IP ]; then exit 1; fi
#PORT=$(docker port $ID 22)

echo $ID > ~/.tor-browser.pid

echo "Run the following to get your SSH Password: "
echo "docker logs $ID 2> /dev/null | head -1"
echo "Then run the following to launch tor-browser: "
echo ssh -oStrictHostKeyChecking=no -oCheckHostIP=no -YC -c blowfish docker@localhost -p $PORT ./tor-browser

