#!/bin/bash


ID=$(docker ps | grep "multikatt/docker-torbrowser" | cut -d" " -f1,1)
if [[ -z $ID ]]; then
    echo "Starting container"
    ID=$(docker run -d "multikatt/docker-torbrowser")
else
    echo "Container already running, ID: $ID"
fi

IP=$(docker inspect $ID | sed -n 's/.*ress": "\(.*\)",$/\1/p')
echo $IP
if [ -z $IP ]; then exit 1; fi
#PORT=$(docker port $ID 22)

echo $ID > ~/.tor-browser.pid

while [[ -z $PASS ]]; do PASS=$(docker logs $ID | head -1); done
echo -e "SSH Credentials:\n$PASS"
echo "Launching tor-browser: "

ssh -oUserKnownHostsFile=/dev/null -oConnectionAttempts=100 -oConnectTimeout=60 -oStrictHostKeyChecking=no -oCheckHostIP=no -YC -c blowfish docker@$IP ./tor-browser

